"use client";
import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";
import { Card, Notice, PageHeader } from "../../../components/admin/AdminUI";

type Business={brand_name:string;whatsapp_number:string;support_email:string;currency:string};
type Commerce={delivery_fee:number;cod_enabled:boolean;minimum_order_value:number};
type Homepage={show_featured_products:boolean;show_categories:boolean;announcement:string};
const field="mt-1.5 min-h-11 w-full rounded-xl border border-[#DCCFC8] px-3 text-sm";
export default function SettingsPage(){const[error,setError]=useState("");const[success,setSuccess]=useState("");const[business,setBusiness]=useState<Business>({brand_name:"carddesign.studio",whatsapp_number:"",support_email:"",currency:"INR"});const[commerce,setCommerce]=useState<Commerce>({delivery_fee:0,cod_enabled:true,minimum_order_value:0});const[homepage,setHomepage]=useState<Homepage>({show_featured_products:true,show_categories:true,announcement:""});
 useEffect(()=>{(async()=>{const r=await supabase.from("site_settings").select("key,value").in("key",["business","commerce","homepage"]);if(r.error){setError(r.error.message);return}(r.data??[]).forEach((row)=>{if(row.key==="business")setBusiness(p=>({...p,...(row.value as Business)}));if(row.key==="commerce")setCommerce(p=>({...p,...(row.value as Commerce)}));if(row.key==="homepage")setHomepage(p=>({...p,...(row.value as Homepage)}))})})()},[]);
 async function save(e:FormEvent){e.preventDefault();setError("");setSuccess("");const{data:{user}}=await supabase.auth.getUser();const rows=[{key:"business",value:business,is_public:true,updated_by:user?.id??null},{key:"commerce",value:commerce,is_public:true,updated_by:user?.id??null},{key:"homepage",value:homepage,is_public:true,updated_by:user?.id??null}];const r=await supabase.from("site_settings").upsert(rows,{onConflict:"key"});if(r.error)setError(r.error.message);else setSuccess("Website settings saved.")}
 return <div className="space-y-6"><PageHeader eyebrow="Configuration" title="Website Settings" description="Central business, commerce and homepage configuration stored in Supabase."/>{error&&<Notice>{error}</Notice>}{success&&<Notice kind="success">{success}</Notice>}<form onSubmit={save} className="grid gap-6 xl:grid-cols-3"><Card className="p-5"><h2 className="font-black">Business</h2><div className="mt-4 space-y-4"><label className="block text-xs font-bold">Brand name<input className={field} value={business.brand_name} onChange={e=>setBusiness(p=>({...p,brand_name:e.target.value}))}/></label><label className="block text-xs font-bold">WhatsApp number<input className={field} placeholder="9198XXXXXXXX" value={business.whatsapp_number} onChange={e=>setBusiness(p=>({...p,whatsapp_number:e.target.value.replace(/\D/g,"")}))}/></label><label className="block text-xs font-bold">Support email<input type="email" className={field} value={business.support_email} onChange={e=>setBusiness(p=>({...p,support_email:e.target.value}))}/></label><label className="block text-xs font-bold">Currency<input className={field} value={business.currency} onChange={e=>setBusiness(p=>({...p,currency:e.target.value.toUpperCase()}))}/></label></div></Card><Card className="p-5"><h2 className="font-black">Commerce</h2><div className="mt-4 space-y-4"><label className="block text-xs font-bold">Delivery fee (₹)<input type="number" min="0" className={field} value={commerce.delivery_fee} onChange={e=>setCommerce(p=>({...p,delivery_fee:Number(e.target.value)}))}/></label><label className="block text-xs font-bold">Minimum order value (₹)<input type="number" min="0" className={field} value={commerce.minimum_order_value} onChange={e=>setCommerce(p=>({...p,minimum_order_value:Number(e.target.value)}))}/></label><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={commerce.cod_enabled} onChange={e=>setCommerce(p=>({...p,cod_enabled:e.target.checked}))}/> Cash on delivery enabled</label></div></Card><Card className="p-5"><h2 className="font-black">Homepage</h2><div className="mt-4 space-y-4"><label className="block text-xs font-bold">Announcement<textarea className={`${field} min-h-24 py-3`} value={homepage.announcement} onChange={e=>setHomepage(p=>({...p,announcement:e.target.value}))}/></label><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={homepage.show_featured_products} onChange={e=>setHomepage(p=>({...p,show_featured_products:e.target.checked}))}/> Show featured products</label><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={homepage.show_categories} onChange={e=>setHomepage(p=>({...p,show_categories:e.target.checked}))}/> Show categories</label></div></Card><div className="xl:col-span-3"><button className="min-h-12 rounded-xl bg-[#8B2E3F] px-7 text-sm font-extrabold text-white">Save website settings</button></div></form></div>
}
