"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

export default function WhatsAppSupportPage(){
 const[whatsapp,setWhatsapp]=useState("");const[name,setName]=useState("");const[phone,setPhone]=useState("");const[email,setEmail]=useState("");const[topic,setTopic]=useState("Customization");const[message,setMessage]=useState("");const[error,setError]=useState("");const[success,setSuccess]=useState("");const[sending,setSending]=useState(false);
 useEffect(()=>{try{const customer=JSON.parse(localStorage.getItem("wedinvite-customer")||"null");if(customer){setName(customer.fullName||"");setPhone(customer.phone||"");setEmail(customer.email||"")}}catch{};(async()=>{const r=await supabase.from("site_settings").select("value").eq("key","business").maybeSingle();const value=r.data?.value as {whatsapp_number?:string}|null;if(value?.whatsapp_number)setWhatsapp(value.whatsapp_number.replace(/\D/g,""))})()},[]);
 async function submit(e:FormEvent){e.preventDefault();setError("");setSuccess("");if(!message.trim()){setError("Tell us what you need help with.");return}setSending(true);const r=await supabase.from("whatsapp_enquiries").insert({customer_name:name.trim()||null,phone:phone.replace(/\D/g,"")||null,email:email.trim()||null,topic,message:message.trim()});setSending(false);if(r.error){setError(r.error.message);return}setSuccess("Your enquiry is saved in the admin dashboard.");if(whatsapp){const text=`Hi carddesign.studio, I need help with ${topic}.\n\n${message.trim()}${name.trim()?`\n\nName: ${name.trim()}`:""}`;window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer")}}
 return <main className="min-h-screen bg-[#FFFDF9] text-[#2B2523]"><section className="mx-auto max-w-5xl px-5 py-12 md:px-8 lg:py-16"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#8B2E3F]">Customer support</p><h1 className="mt-2 text-4xl font-black tracking-tight md:text-5xl">WhatsApp support</h1><p className="mt-3 max-w-2xl leading-7 text-[#756B67]">Send an enquiry to the dashboard and, when the business WhatsApp number is configured in Website Settings, open the same message in WhatsApp.</p>
 {error&&<div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{success&&<div className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{success}</div>}
 <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><form onSubmit={submit} className="rounded-3xl border border-[#E8DDD6] bg-white p-5 sm:p-6"><h2 className="text-lg font-black">How can we help?</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-extrabold">Name<input className="mt-1.5 min-h-11 w-full rounded-xl border border-[#DCCFC8] px-3" value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-xs font-extrabold">Mobile<input className="mt-1.5 min-h-11 w-full rounded-xl border border-[#DCCFC8] px-3" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="text-xs font-extrabold">Email<input type="email" className="mt-1.5 min-h-11 w-full rounded-xl border border-[#DCCFC8] px-3" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="text-xs font-extrabold">Topic<select className="mt-1.5 min-h-11 w-full rounded-xl border border-[#DCCFC8] px-3" value={topic} onChange={e=>setTopic(e.target.value)}><option>Customization</option><option>Order</option><option>Printing & quality</option><option>Delivery & tracking</option><option>Payment</option><option>General question</option></select></label><label className="text-xs font-extrabold sm:col-span-2">Message<textarea className="mt-1.5 min-h-36 w-full rounded-xl border border-[#DCCFC8] p-3" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Describe your question..."/></label></div><button disabled={sending} className="mt-5 min-h-12 w-full rounded-xl bg-[#8B2E3F] text-sm font-extrabold text-white disabled:opacity-60">{sending?"Saving enquiry...":whatsapp?"Save & open WhatsApp":"Save enquiry"}</button>{!whatsapp&&<p className="mt-3 text-xs leading-5 text-amber-700">Admin has not configured a WhatsApp number yet. The enquiry will still be saved.</p>}</form><aside className="space-y-4"><div className="rounded-3xl bg-[#8B2E3F] p-6 text-white"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#E8CFA5]">Support flow</p><h2 className="mt-2 text-2xl font-black">Every enquiry is trackable.</h2><p className="mt-3 text-sm leading-6 text-white/80">Admin can move requests through New → Contacted → Resolved → Closed from the dashboard.</p></div>{[["Customization","Names, wording, language, venue and proof help."],["Orders","Order status, quantity, address and fulfilment help."],["Printing","Paper, finish, size and print-quality questions."]].map(([title,copy])=><div key={title} className="rounded-2xl border border-[#E8DDD6] bg-white p-4"><p className="font-black">{title}</p><p className="mt-1 text-sm leading-6 text-[#756B67]">{copy}</p></div>)}</aside></div></section></main>
}
