"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type TrackedOrder = { order_number: string; order_status: string; payment_status: string; total_amount: number; tracking_number: string | null; courier_name: string | null; created_at: string; shipped_at: string | null; delivered_at: string | null };
const steps = ["placed","confirmed","designing","proof_sent","printing","ready","shipped","delivered"];

export default function TrackOrderPage(){
 const[orderNumber,setOrderNumber]=useState("");const[phone,setPhone]=useState("");const[order,setOrder]=useState<TrackedOrder|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{try{const last=JSON.parse(localStorage.getItem("wedinvite-last-order")||"null");if(last?.id)setOrderNumber(last.id);if(last?.customer?.phone)setPhone(last.customer.phone)}catch{}},[]);
 async function track(e:FormEvent){e.preventDefault();setError("");setOrder(null);const cleanPhone=phone.replace(/\D/g,"");if(!orderNumber.trim()||!/^[6-9]\d{9}$/.test(cleanPhone)){setError("Enter your order number and the 10-digit mobile number used at checkout.");return}setLoading(true);const r=await supabase.rpc("track_order_by_phone",{p_order_number:orderNumber.trim(),p_phone:cleanPhone});setLoading(false);if(r.error){setError(r.error.message);return}const row=(r.data??[])[0] as TrackedOrder|undefined;if(!row){setError("No matching order found. Check the order number and mobile number.");return}setOrder(row)}
 const currentIndex=order?steps.indexOf(order.order_status):-1;
 return <main className="min-h-screen bg-[#FFFDF9] text-[#2B2523]"><section className="mx-auto max-w-4xl px-5 py-12 md:px-8 lg:py-16"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#8B2E3F]">Order tracking</p><h1 className="mt-2 text-4xl font-black tracking-tight md:text-5xl">Track your wedding cards</h1><p className="mt-3 max-w-2xl leading-7 text-[#756B67]">Enter the order number and mobile number used during checkout. Status comes directly from Supabase.</p>
 <form onSubmit={track} className="mt-8 grid gap-3 rounded-3xl border border-[#E8DDD6] bg-white p-5 sm:grid-cols-[1fr_1fr_auto] sm:p-6"><input className="min-h-12 rounded-xl border border-[#DCCFC8] px-4 text-sm" placeholder="Order number e.g. CDS..." value={orderNumber} onChange={e=>setOrderNumber(e.target.value)}/><input className="min-h-12 rounded-xl border border-[#DCCFC8] px-4 text-sm" inputMode="numeric" placeholder="Mobile number" value={phone} onChange={e=>setPhone(e.target.value)}/><button disabled={loading} className="min-h-12 rounded-xl bg-[#8B2E3F] px-6 text-sm font-extrabold text-white disabled:opacity-60">{loading?"Checking...":"Track order"}</button></form>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
 {order&&<div className="mt-8 space-y-6"><div className="rounded-3xl border border-[#E8DDD6] bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wide text-[#817672]">Order</p><h2 className="mt-1 text-2xl font-black text-[#8B2E3F]">{order.order_number}</h2><p className="mt-1 text-xs text-[#756B67]">Placed {new Date(order.created_at).toLocaleString("en-IN")}</p></div><div className="text-right"><p className="text-xs font-black uppercase tracking-wide text-[#817672]">Total</p><p className="mt-1 text-xl font-black">₹{Number(order.total_amount).toLocaleString("en-IN")}</p><p className="mt-1 text-xs font-bold capitalize text-[#756B67]">Payment: {order.payment_status.replaceAll("_"," ")}</p></div></div></div>
 <div className="rounded-3xl border border-[#E8DDD6] bg-white p-5 sm:p-6"><h3 className="font-black">Order progress</h3><div className="mt-6 grid gap-0">{steps.map((step,index)=>{const done=currentIndex>=index;const active=currentIndex===index;return <div key={step} className="flex gap-4"><div className="flex flex-col items-center"><div className={`flex h-8 w-8 items-center justify-center rounded-full border-2 text-xs font-black ${done?"border-[#8B2E3F] bg-[#8B2E3F] text-white":"border-[#D9CCC5] bg-white text-[#A09691]"}`}>{done?"✓":index+1}</div>{index<steps.length-1&&<div className={`h-10 w-0.5 ${currentIndex>index?"bg-[#8B2E3F]":"bg-[#E8DDD6]"}`}/>}</div><div className="pt-1"><p className={`text-sm font-black capitalize ${active?"text-[#8B2E3F]":""}`}>{step.replaceAll("_"," ")}</p>{active&&<p className="mt-1 text-xs text-[#756B67]">Current stage</p>}</div></div>})}</div>{order.order_status==="cancelled"&&<div className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">This order has been cancelled.</div>}</div>
 {(order.tracking_number||order.courier_name)&&<div className="rounded-3xl border border-[#E8DDD6] bg-[#F8F0EB] p-5"><p className="text-xs font-black uppercase tracking-wide text-[#8B2E3F]">Shipping</p><p className="mt-2 font-black">{order.courier_name||"Courier"}</p><p className="mt-1 text-sm text-[#756B67]">Tracking number: {order.tracking_number||"Pending"}</p></div>}</div>}
 </section></main>
}
