"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../../../lib/supabase";
import { Card, EmptyState, Notice, PageHeader, StatusBadge } from "../../../components/admin/AdminUI";

type Category = { id: string; name: string; slug: string; description: string | null; image_url: string | null; parent_id: string | null; sort_order: number; is_active: boolean; is_featured: boolean; show_in_navigation: boolean; show_on_homepage: boolean };
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""); }
const input = "mt-1.5 min-h-11 w-full rounded-xl border border-[#DCCFC8] px-3 text-sm outline-none focus:border-[#8B2E3F]";

export default function CategoriesPage() {
  const [rows, setRows] = useState<Category[]>([]); const [error, setError] = useState(""); const [editing, setEditing] = useState<Category | null>(null); const [uploading, setUploading] = useState(false);
  const [form, setForm] = useState({ name: "", slug: "", description: "", image_url: "", parent_id: "", sort_order: "0", is_active: true, is_featured: false, show_in_navigation: true, show_on_homepage: true });
  async function load() { const result = await supabase.from("categories").select("id,name,slug,description,image_url,parent_id,sort_order,is_active,is_featured,show_in_navigation,show_on_homepage").is("deleted_at", null).order("sort_order").order("name"); if (result.error) setError(result.error.message); else setRows((result.data ?? []) as Category[]); }
  useEffect(() => { load(); }, []);
  const parentOptions = useMemo(() => rows.filter((row) => row.id !== editing?.id), [rows, editing]);
  function reset() { setEditing(null); setForm({ name: "", slug: "", description: "", image_url: "", parent_id: "", sort_order: "0", is_active: true, is_featured: false, show_in_navigation: true, show_on_homepage: true }); }
  function edit(row: Category) { setEditing(row); setForm({ name: row.name, slug: row.slug, description: row.description ?? "", image_url: row.image_url ?? "", parent_id: row.parent_id ?? "", sort_order: String(row.sort_order), is_active: row.is_active, is_featured: row.is_featured, show_in_navigation: row.show_in_navigation, show_on_homepage: row.show_on_homepage }); }
  async function upload(file: File | null) { if (!file) return; if (!["image/jpeg","image/png","image/webp"].includes(file.type) || file.size > 6*1024*1024) { setError("Category image must be JPG, PNG or WebP and 6 MB or smaller."); return; } setUploading(true); const ext=file.name.split(".").pop()?.toLowerCase()||"jpg"; const path=`categories/${crypto.randomUUID()}.${ext}`; const result=await supabase.storage.from("catalog-images").upload(path,file,{contentType:file.type}); if(result.error)setError(result.error.message); else { const {data}=supabase.storage.from("catalog-images").getPublicUrl(path); setForm((p)=>({...p,image_url:data.publicUrl})); } setUploading(false); }
  async function save(e: FormEvent) { e.preventDefault(); setError(""); if (!form.name.trim()) { setError("Category name is required."); return; } const payload = { ...form, name: form.name.trim(), slug: slugify(form.slug || form.name), description: form.description.trim() || null, image_url: form.image_url || null, parent_id: form.parent_id || null, sort_order: Number(form.sort_order) || 0 }; const result = editing ? await supabase.from("categories").update(payload).eq("id", editing.id) : await supabase.from("categories").insert(payload); if (result.error) setError(result.error.message); else { reset(); load(); } }
  async function remove(row: Category) { if (!confirm(`Archive category ${row.name}? Products will remain in the catalog.`)) return; const result = await supabase.from("categories").update({ deleted_at: new Date().toISOString(), is_active: false }).eq("id", row.id); if (result.error) setError(result.error.message); else load(); }

  return <div className="space-y-6"><PageHeader eyebrow="Catalog" title="Categories" description="Create parent/subcategories, upload collection images and control navigation/homepage visibility." />{error && <Notice>{error}</Notice>}
    <div className="grid gap-6 xl:grid-cols-[390px_minmax(0,1fr)]"><Card className="p-5 xl:sticky xl:top-8 xl:self-start"><h2 className="text-lg font-black">{editing ? "Edit category" : "Add category"}</h2><form onSubmit={save} className="mt-5 space-y-4">
      <label className="block text-xs font-extrabold">Name<input className={input} value={form.name} onChange={(e) => setForm((p) => ({ ...p, name: e.target.value, slug: editing ? p.slug : slugify(e.target.value) }))} /></label><label className="block text-xs font-extrabold">Slug<input className={input} value={form.slug} onChange={(e) => setForm((p) => ({ ...p, slug: slugify(e.target.value) }))} /></label>
      <label className="block cursor-pointer rounded-xl border border-dashed border-[#CDB7AB] bg-[#FCF8F5] p-4 text-center text-xs font-extrabold text-[#8B2E3F]">{uploading?"Uploading...":form.image_url?"Replace category image":"Upload category image"}<input type="file" className="hidden" accept="image/jpeg,image/png,image/webp" onChange={(e)=>upload(e.target.files?.[0]??null)}/></label>{form.image_url&&<img src={form.image_url} alt="Category preview" className="aspect-[4/2.4] w-full rounded-xl object-cover"/>}
      <label className="block text-xs font-extrabold">Parent category<select className={input} value={form.parent_id} onChange={(e) => setForm((p) => ({ ...p, parent_id: e.target.value }))}><option value="">None</option>{parentOptions.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className="block text-xs font-extrabold">Sort order<input type="number" className={input} value={form.sort_order} onChange={(e) => setForm((p) => ({ ...p, sort_order: e.target.value }))} /></label><label className="block text-xs font-extrabold">Description<textarea className={`${input} min-h-24 py-3`} value={form.description} onChange={(e) => setForm((p) => ({ ...p, description: e.target.value }))} /></label>
      {([['is_active','Active'],['is_featured','Featured'],['show_in_navigation','Show in navigation'],['show_on_homepage','Show on homepage']] as const).map(([key,label]) => <label key={key} className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={form[key]} onChange={(e) => setForm((p) => ({ ...p, [key]: e.target.checked }))} />{label}</label>)}
      <button className="min-h-11 w-full rounded-xl bg-[#8B2E3F] text-sm font-extrabold text-white">{editing ? "Save changes" : "Create category"}</button>{editing && <button type="button" onClick={reset} className="min-h-11 w-full rounded-xl border border-[#DCCFC8] text-sm font-bold">Cancel</button>}
    </form></Card>
    <Card className="overflow-hidden">{rows.length === 0 ? <EmptyState title="No categories" description="Use the form to create the first category." /> : <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-[#FCF8F5] text-[11px] uppercase tracking-wide text-[#817672]"><tr><th className="px-4 py-3">Category</th><th className="px-4 py-3">Parent</th><th className="px-4 py-3">Order</th><th className="px-4 py-3">Visibility</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#F0E7E2]">{rows.map((row) => <tr key={row.id}><td className="px-4 py-4"><div className="flex items-center gap-3"><div className="h-12 w-16 overflow-hidden rounded-lg bg-[#F0E4DC]">{row.image_url&&<img src={row.image_url} alt="" className="h-full w-full object-cover"/>}</div><div><p className="font-black">{row.name}</p><p className="text-xs text-[#756B67]">/{row.slug}</p></div></div></td><td className="px-4 py-4">{rows.find((parent) => parent.id === row.parent_id)?.name ?? "—"}</td><td className="px-4 py-4">{row.sort_order}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-1"><StatusBadge value={row.is_active ? "active" : "inactive"} />{row.is_featured && <span className="rounded-full bg-amber-50 px-2 py-1 text-[11px] font-extrabold text-amber-700">Featured</span>}{row.show_in_navigation && <span className="rounded-full bg-blue-50 px-2 py-1 text-[11px] font-extrabold text-blue-700">Nav</span>}{row.show_on_homepage&&<span className="rounded-full bg-purple-50 px-2 py-1 text-[11px] font-extrabold text-purple-700">Home</span>}</div></td><td className="px-4 py-4"><div className="flex justify-end gap-2"><button onClick={() => edit(row)} className="rounded-lg border border-[#DCCFC8] px-3 py-2 text-xs font-bold">Edit</button><button onClick={() => remove(row)} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700">Archive</button></div></td></tr>)}</tbody></table></div>}</Card></div>
  </div>;
}
