"use client";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../../lib/supabase";
import { Card, EmptyState, Notice, PageHeader } from "../../../components/admin/AdminUI";

type Profile = { id: string; full_name: string | null; email: string | null; phone: string | null; city: string | null; state: string | null; created_at: string };
type Order = { user_id: string | null; total_amount: number; payment_status: string };
export default function CustomersPage() {
  const [profiles, setProfiles] = useState<Profile[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [error, setError] = useState(""); const [search, setSearch] = useState("");
  useEffect(() => { (async () => { const [p,o]=await Promise.all([supabase.from("profiles").select("id,full_name,email,phone,city,state,created_at").order("created_at",{ascending:false}),supabase.from("orders").select("user_id,total_amount,payment_status")]); if(p.error)setError(p.error.message); else setProfiles((p.data??[]) as Profile[]); setOrders((o.data??[]) as Order[]); })(); }, []);
  const filtered=useMemo(()=>profiles.filter((p)=>`${p.full_name??""} ${p.email??""} ${p.phone??""}`.toLowerCase().includes(search.toLowerCase())),[profiles,search]);
  const metrics=(id:string)=>{const rows=orders.filter((o)=>o.user_id===id);return{orders:rows.length,spent:rows.filter((o)=>o.payment_status==="paid").reduce((s,o)=>s+Number(o.total_amount||0),0)}};
  return <div className="space-y-6"><PageHeader eyebrow="CRM" title="Customers" description="Registered customer profiles with order count and paid lifetime value." />{error&&<Notice>{error}</Notice>}<Card className="p-4"><input className="min-h-11 w-full rounded-xl border border-[#DCCFC8] px-4 text-sm" placeholder="Search name, email or phone..." value={search} onChange={(e)=>setSearch(e.target.value)} /></Card><Card className="overflow-hidden">{filtered.length===0?<EmptyState title="No customers found" description="Registered profiles will appear here."/>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#FCF8F5] text-[11px] uppercase tracking-wide text-[#817672]"><tr><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Phone</th><th className="px-4 py-3">Location</th><th className="px-4 py-3">Orders</th><th className="px-4 py-3">Paid LTV</th><th className="px-4 py-3">Joined</th></tr></thead><tbody className="divide-y divide-[#F0E7E2]">{filtered.map((p)=>{const m=metrics(p.id);return <tr key={p.id}><td className="px-4 py-4"><p className="font-black">{p.full_name||"Unnamed customer"}</p><p className="text-xs text-[#756B67]">{p.email||"—"}</p></td><td className="px-4 py-4">{p.phone||"—"}</td><td className="px-4 py-4">{[p.city,p.state].filter(Boolean).join(", ")||"—"}</td><td className="px-4 py-4 font-bold">{m.orders}</td><td className="px-4 py-4 font-black">₹{m.spent.toLocaleString("en-IN")}</td><td className="px-4 py-4 text-xs text-[#756B67]">{new Date(p.created_at).toLocaleDateString("en-IN")}</td></tr>})}</tbody></table></div>}</Card></div>
}
